name: build faas release native
on:
  push:
    branches:
      - main
jobs:
  build:
    name: plugin relase package ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-22.04,ubuntu-24.04-arm,macos-13,macos-14,windows-2022]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install UPX
        uses: crazy-max/ghaction-upx@v3
        with:
          install-only: true
      - name: UPX version
        run: upx --version
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm' # See 'Options' for all available distributions
          cache: 'maven'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'

      - name: Build and upload binary
        run: |
          bash -e bin/package-native-github.sh /tmp/download/plugin/core/faas -Dmysql-scope='provided'
          bash -e bin/upload-bin.sh ${{ secrets.SECRET_ID }} ${{ secrets.SECRET_KEY }} ${{ secrets.BUCKET }} /tmp/download plugin ${{ secrets.HOST }}